package io.k8cluster.microservices.modules.access.model;

public enum ROLE {
    SYSTEM_ADMINISTRATOR,
    PRINT_SHOP_SALES_ENGINEER,
    PRINT_SHOP_ADMINISTRATOR,
    PART_BUYER_PART_BUYER,
    PART_BUYER_ADMINISTRATOR,
    ORGANIZATION_ADMINISTRATOR,
    DATA_MANAGER,
    COMPANY_ADMIN,
    PRODUCTION_PLANNER,
    SERVICE_ACCOUNT_IMPORT,
    SERVICE_ACCOUNT_PRODUCTION
}
